enum DocumentUnitReferenceTypeEnum {
    Fascicle = 0,
    FascicleProtocol = 1,
    Dossier = 2,
    Atti = 3,
    PECIncoming = 4,
    PECOutgoing = 5,
    Archive = 6,
    ArchiveProtocol = 7,
    Protocol = 8,
    ProtocolLinks = 9,
    ProtocolSeries = 10,
    MessageResolution = 11,
    MessageProtocol = 12,
    MessageSeries = 13,
    SeriesProtocol = 14,
    Series = 15,
    Workflows = 16,
    Process = 17,
    TNotice = 18,
    DoneWorkflows = 19,
    PECUnified = 20,
    DeletedFascicleDocumentUnit = 21,
    DeletedFascicleDocument = 22,
    FascicleDocumentUnitLink = 23,
}

export = DocumentUnitReferenceTypeEnum