'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReslPecOcAdd

    '''<summary>
    '''dataPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataPanel As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ReslType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReslType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents From As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateFrom As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rowExtractOneDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowExtractOneDay As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''extractOneDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents extractOneDay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkExtractOneDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExtractOneDay As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DateToRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateToRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''To control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents [To] As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateTo As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''ExtractAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtractAttachment As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Conferma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Conferma As Global.System.Web.UI.WebControls.Button
End Class
