'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReslProposedPrint
    
    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''pnlHeaders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeaders As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlTipologia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTipologia As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rblTipologia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTipologia As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSession As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SessionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SessionDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rfvAdoptionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAdoptionDate As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlAdottataIntervallo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdottataIntervallo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''AdoptionDate_From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdoptionDate_From As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rfvAdoptionDate_From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAdoptionDate_From As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''AdoptionDate_To control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdoptionDate_To As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rfvAdoptionDate_To control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAdoptionDate_To As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlGestione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGestione As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkCollegio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCollegio As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlControls As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlContenitoreTvw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlContenitoreTvw As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSelectAll As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeselectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeselectAll As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tvwContenitore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvwContenitore As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''cmdStampa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdStampa As Global.System.Web.UI.WebControls.Button
End Class
