'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReslInserimento

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadWindowManagerProtocollo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManagerProtocollo As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''windowSelProtocollo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelProtocollo As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''windowSelContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelContact As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''windowSelDraftSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelDraftSeries As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''windowSelRoleCollaborationProposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelRoleCollaborationProposer As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''rtvRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtvRoles As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''btnSelectRoleProposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSelectRoleProposer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlResolutionContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResolutionContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblResolutionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblResolutionNumber As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rblProposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblProposta As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblDocumentCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocumentCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uscUploadDocumenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscUploadDocumenti As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload

    '''<summary>
    '''mainDocumentOmissisTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainDocumentOmissisTr As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDocumentOmissisCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocumentOmissisCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uscUploadDocumentiOmissis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscUploadDocumentiOmissis As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload

    '''<summary>
    '''pnlAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAttach As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAttachmentsCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAttachmentsCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uscUploadAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscUploadAttach As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload

    '''<summary>
    '''attachmentOmissisTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attachmentOmissisTr As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblAttachmentsOmissisCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAttachmentsOmissisCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uscUploadAttachOmissis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscUploadAttachOmissis As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload

    '''<summary>
    '''pnlPrivacyAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPrivacyAttachment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPrivacyAttachmentCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrivacyAttachmentCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uscUploadPrivacyAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscUploadPrivacyAttachment As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload

    '''<summary>
    '''lblAnnexedCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexedCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uscUploadAnnexed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscUploadAnnexed As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload

    '''<summary>
    '''pnlImmediatelyExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImmediatelyExecutive As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkImmediatelyExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImmediatelyExecutive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlAUSLREOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAUSLREOC As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkAUSLREOCNonSoggetta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAUSLREOCNonSoggetta As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAUSLREOCSoggetta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAUSLREOCSoggetta As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cvControllaAUSLREOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvControllaAUSLREOC As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''idContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idContainer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ContenitoreValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContenitoreValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlResolutionKind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResolutionKind As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlResolutionKind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResolutionKind As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlResolutionKindValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResolutionKindValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlAccounting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAccounting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBidTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBidTypes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rlbBidTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlbBidTypes As Global.Telerik.Web.UI.RadDropDownList

    '''<summary>
    '''pnlAdozione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdozione As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chbAdoption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chbAdoption As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlAdozioneData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdozioneData As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rdpDataAdozione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpDataAdozione As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rfvData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvData As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlAdozioneNumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdozioneNumero As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtServiceNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServiceNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvServiceNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvServiceNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revNumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumero As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''TblDestinatari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TblDestinatari As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''pnlDestInterop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDestInterop As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''uscDestinatari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscDestinatari As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel

    '''<summary>
    '''uscDestinatariAlt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscDestinatariAlt As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSelText

    '''<summary>
    '''tblCollaborationAuthorize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCollaborationAuthorize As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''collaborationAuthorizedRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collaborationAuthorizedRoles As Global.VecompSoftware.DocSuiteWeb.Gui.uscSettori

    '''<summary>
    '''pnlProposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProposer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlProponenteInterop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProponenteInterop As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''SelProponente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelProponente As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel

    '''<summary>
    '''uscRoleProposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscRoleProposer As Global.VecompSoftware.DocSuiteWeb.Gui.uscSettori

    '''<summary>
    '''SelProponenteAlt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelProponenteAlt As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSelText

    '''<summary>
    '''proposerGeneralValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents proposerGeneralValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''pnlAssegnatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAssegnatario As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlAsseInterop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAsseInterop As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SelAssegnatario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelAssegnatario As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel

    '''<summary>
    '''SelAssegnatarioAlt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelAssegnatarioAlt As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSelText

    '''<summary>
    '''pnlResponsabile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResponsabile As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlRespInterop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRespInterop As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SelResponsabile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelResponsabile As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel

    '''<summary>
    '''SelResponsabileAlt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelResponsabileAlt As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSelText

    '''<summary>
    '''pnlObjectPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlObjectPrivacy As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblObjectPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObjectPrivacy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelOggettoPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelOggettoPrivacy As Global.VecompSoftware.DocSuiteWeb.Gui.uscOggetto

    '''<summary>
    '''SelOggetto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelOggetto As Global.VecompSoftware.DocSuiteWeb.Gui.uscOggetto

    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''pnlAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAmount As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rfvAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAmount As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlAutorizzazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAutorizzazioni As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''uscSettori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscSettori As Global.VecompSoftware.DocSuiteWeb.Gui.uscSettori

    '''<summary>
    '''pnlOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOC As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlOCSupervisoryBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCSupervisoryBoard As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkOCSupervisoryBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCSupervisoryBoard As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlOCConfSindaci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCConfSindaci As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkOCConfSindaci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCConfSindaci As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlOCRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCRegion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkOCRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCRegion As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlOCManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCManagement As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkOCManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCManagement As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlOCCorteConti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCCorteConti As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkOCCorteConti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCCorteConti As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlOCOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCOther As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkOCOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCOther As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOCOtherDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOCOtherDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCategory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''uscSelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscSelCategory As Global.VecompSoftware.DocSuiteWeb.Gui.uscClassificatore

    '''<summary>
    '''pnlAmmTrasp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAmmTrasp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dgvResolutionKindDocumentSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvResolutionKindDocumentSeries As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''pnlButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnInserimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInserimento As Global.System.Web.UI.WebControls.Button
End Class
