import PECMailBoxViewModel = require('App/ViewModels/PECMails/PECMailBoxViewModel');
import LocationViewModel = require('App/ViewModels/Commons/LocationViewModel');
import PECMailReceiptsModel = require('App/ViewModels/PECMails/PECMailReceiptsModel');

class PECMailViewModel {
    EntityShortId: number;
    Direction: number;
    Year?: number;
    Number?: number;
    MailUID: string;
    MailContent: string;
    MailSubject: string;
    MailSenders: string;
    MailRecipients: string;
    MailDate: string;
    MailType: string;
    MailError: string;
    MailPriority?: number;
    XTrasporto: string;
    MessageID: string;
    XRiferimentoMessageID: string;
    Segnatura: string;
    MessaggioRitornoName: string;
    MessaggioRitornoStream: string;
    MailBody: string;
    RecordedInDocSuite?: number;
    ContentLength?: number;
    IsToForward: boolean;
    IsValidForInterop: boolean;
    IsActive: boolean;
    MailStatus?: number;
    IsDestinated: boolean;
    DestinationNote: string;
    Handler: string;
    IDAttachments: string;
    IDDaticert: string;
    IDEnvelope: string;
    IDMailContent: string;
    IDPostacert: string;
    IDSegnatura: string;
    IDSmime: string;
    PECType?: number;
    Checksum: string;
    Multiple: boolean;
    SplittedFrom?: number;
    OriginalRecipient: string;
    HeaderChecksum: string;
    ProcessStatus?: number;
    MailRecipientsCc: string;
    ReceivedAsCc?: boolean;
    Size?: number;
    MultipleType?: number;
    DocumentUnitType?: number;
    IdUDS?: string;
    InvoiceStatus: string;
    InvoiceStatusDescription: string;
    EntityId: number;
    UniqueId: string;
    RegistrationUser: string;
    RegistrationDate?: Date;
    LastChangedUser: string;
    LastChangedDate?: Date;
    InvoiceTypeDescription: string;
    Location: LocationViewModel;
    PECMailBox: PECMailBoxViewModel;
    PECMailReceipts: PECMailReceiptsModel[];
}

export = PECMailViewModel;