'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DocmTokenPresaCarico

    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadWindowManagerToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManagerToken As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''windowRifiuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowRifiuta As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''docmContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents docmContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''uscDocumentToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscDocumentToken As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentToken

    '''<summary>
    '''pnlRestituzione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRestituzione As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtReasonResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReasonResponse As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''pnlSettoriInAttesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSettoriInAttesa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''radTreeSettoriInAttesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radTreeSettoriInAttesa As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''pnlDistribuzione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDistribuzione As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''uscDistribuzione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscDistribuzione As Global.VecompSoftware.DocSuiteWeb.Gui.uscSettoriUtente

    '''<summary>
    '''pnlRifiuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRifiuto As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgRifiuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRifiuta As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtRefusal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefusal As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnAccetta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAccetta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRifiuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRifiuta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtProgrIncremental control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgrIncremental As Global.System.Web.UI.WebControls.TextBox
End Class
