'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VecompSoftware.DocSuiteWeb.Data.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property AbsentManagersCertificates() As String
            Get
                Return ResourceManager.GetString("AbsentManagersCertificates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [
        '''  {
        '''    &quot;ViewName&quot;: &quot;AllaVisioneFirma&quot;,
        '''    &quot;ColumnsVisibility&quot;: {
        '''      &quot;Entity.IdCollaboration&quot;: false,
        '''      &quot;ClientSelectColumn&quot;: false,
        '''      &quot;cDocType&quot;: true,
        '''      &quot;cDelete&quot;: true,
        '''      &quot;cPriority&quot;: true,
        '''      &quot;cPerson&quot;: false, 
        '''      &quot;cType&quot;: true,
        '''      &quot;cDocSign&quot;: true,
        '''      &quot;cUserDocSign&quot;: false,
        '''      &quot;VersioningCount&quot;: true,
        '''      &quot;Number&quot;: false,
        '''      &quot;Entity.MemorandumDate&quot;: true,
        '''      &quot;Entity.Subject&quot;: true,
        '''      &quot;Entity.Note&quot;: true,
        '''      &quot;Proposer&quot;: true,
        '''      &quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CollaborationGridColumns() As String
            Get
                Return ResourceManager.GetString("CollaborationGridColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [].
        '''</summary>
        Friend ReadOnly Property DocumentSeriesConfigurationOrder() As String
            Get
                Return ResourceManager.GetString("DocumentSeriesConfigurationOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;Miscellanea&quot; : &quot;Miscellanea&quot;,
        '''	&quot;MainChain&quot;: &quot;Documenti&quot;,
        '''	&quot;AttachmentsChain&quot; : &quot;Allegati (parte integrante)&quot;,
        '''	&quot;AnnexedChain&quot;: &quot;Annessi (non parte integrante)&quot;,
        '''	&quot;UnpublishedAnnexedChain&quot;: &quot;Annessi da non pubblicare&quot;,
        '''	&quot;ProposalChain&quot; : &quot;Proposta&quot;,
        '''	&quot;ControllerChain&quot; : &quot;Risposta Organo Controllo&quot;,
        '''	&quot;AssumedProposalChain&quot; : &quot;Proposta assunta&quot;,
        '''	&quot;FrontespizioChain&quot; : &quot;Fronte spizio&quot;,
        '''	&quot;PrivacyAttachmentChain&quot; : &quot;Allegati riservati&quot;,
        '''	&quot;FrontalinoRitiroChain&quot; : &quot;Frontalino&quot;,
        '''	&quot;PrivacyPublication [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DocumentUnitDocumentsLabel() As String
            Get
                Return ResourceManager.GetString("DocumentUnitDocumentsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;ProdecureRoleName&quot;: &quot;Responsabile di procedimento&quot;,
        '''  &quot;SecretaryRoleName&quot;: &quot;Segreteria di procedimento&quot;
        '''}.
        '''</summary>
        Friend ReadOnly Property FascicleRoleLabels() As String
            Get
                Return ResourceManager.GetString("FascicleRoleLabels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;FasciclesLinkedPanelVisibility&quot;: true,
        '''	&quot;GridSearchPanelVisibility&quot;: true
        '''}.
        '''</summary>
        Friend ReadOnly Property FasciclesPanelVisibilities() As String
            Get
                Return ResourceManager.GetString("FasciclesPanelVisibilities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;IsActive&quot;: false,
        '''	&quot;GroupList&quot;: { }
        '''}.
        '''</summary>
        Friend ReadOnly Property HighlightProtocolGroups() As String
            Get
                Return ResourceManager.GetString("HighlightProtocolGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [&quot;Critico&quot;,&quot;Basso&quot;,&quot;Medio&quot;,&quot;Buono&quot;].
        '''</summary>
        Friend ReadOnly Property MonitoringTransparentRatings() As String
            Get
                Return ResourceManager.GetString("MonitoringTransparentRatings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [
        '''  {
        '''    &quot;ViewName&quot;: &quot;PECIncomingMails&quot;,
        '''    &quot;ColumnsVisibility&quot;: {
        '''      &quot;ViewSummary&quot;: true,
        '''      &quot;ViewDocs&quot;: true,
        '''      &quot;AttachmentsCount&quot;: true, 
        '''      &quot;cDirection&quot;: true,
        '''      &quot;cPriority&quot;: true,
        '''      &quot;cInterop&quot;: true,
        '''      &quot;cProtocol&quot;: true,
        '''      &quot;cIsPEC&quot;: true,
        '''      &quot;cMoved&quot;: true,
        '''      &quot;Reply&quot;: true,
        '''      &quot;Forward&quot;: true,
        '''      &quot;Handler&quot;: false,
        '''      &quot;cIsCc&quot;: false,
        '''      &quot;Da&quot;: true,
        '''      &quot;colRecipients&quot;: false,
        '''      &quot;colMailBoxName&quot;: false,
        '''      &quot;MailSubject&quot;: true, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PECInOutColumns() As String
            Get
                Return ResourceManager.GetString("PECInOutColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [
        '''  {
        '''    &quot;Name&quot;: &quot;Anno&quot;,
        '''    &quot;Id&quot;: &quot;txtYear&quot;,
        '''    &quot;Label&quot;: &quot;Anno&quot;
        '''  },
        '''  {
        '''    &quot;Name&quot;: &quot;Numero&quot;,
        '''    &quot;Id&quot;: &quot;txtNumber&quot;,
        '''    &quot;Label&quot;: &quot;Numero&quot;
        '''  },
        '''  {
        '''    &quot;Name&quot;: &quot;Data&quot;,
        '''    &quot;Id&quot;: &quot;txtRegistrationDateFrom&quot;,
        '''    &quot;Label&quot;: &quot;Data&quot;
        '''  },
        '''  {
        '''    &quot;Name&quot;: &quot;DaLeggere&quot;,
        '''    &quot;Id&quot;: &quot;chbNoRead&quot;,
        '''    &quot;Label&quot;: &quot;Da leggere&quot;
        '''  },
        '''  {
        '''    &quot;Name&quot;: &quot;Tipo&quot;,
        '''    &quot;Id&quot;: &quot;ddlType&quot;,
        '''    &quot;Label&quot;: &quot;Tipo&quot;
        '''  },
        '''  {
        '''    &quot;Name&quot;: &quot;Locazione&quot;,
        '''    &quot;Id&quot;: &quot;ddlLocation&quot;,
        '''    &quot;Label&quot;: &quot;Locazione&quot;
        '''  },
        '''  {
        '''    &quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ProtocolAdaptiveSearchMapping() As String
            Get
                Return ResourceManager.GetString("ProtocolAdaptiveSearchMapping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;SearchControls&quot;: {
        '''		&quot;Anno&quot;: &quot;&quot;,
        '''		&quot;Numero&quot;: &quot;&quot;,
        '''		&quot;Data&quot;: &quot;&quot;,
        '''		&quot;Tipo&quot;: &quot;&quot;,
        '''		&quot;Contenitore&quot;: &quot;&quot;,
        '''		&quot;Oggetto&quot;: &quot;&quot;
        '''	},
        '''	&quot;Affinity&quot;: 7
        '''}.
        '''</summary>
        Friend ReadOnly Property ProtocolDefaultAdaptiveSearch() As String
            Get
                Return ResourceManager.GetString("ProtocolDefaultAdaptiveSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [-1,0].
        '''</summary>
        Friend ReadOnly Property ProtocolDistributionTypologies() As String
            Get
                Return ResourceManager.GetString("ProtocolDistributionTypologies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;NoFilter&quot;:  &quot;Nessun filtro&quot;,
        '''  &quot;Contains&quot;: &quot;Contiene&quot;,
        '''  &quot;DoesNotContain&quot;: &quot;Non contiene&quot;,
        '''  &quot;StartsWith&quot;: &quot;Inizia con&quot;,
        '''  &quot;EndsWith&quot;: &quot;Finisce con&quot;,
        '''  &quot;EqualTo&quot;: &quot;Uguale a&quot;,
        '''  &quot;NotEqualTo&quot;: &quot;Diverso da&quot;,
        '''  &quot;GreaterThan&quot;: &quot;Maggiore di&quot;,
        '''  &quot;LessThan&quot;: &quot;Minore di&quot;,
        '''  &quot;GreaterThanOrEqualTo&quot;: &quot;Maggiore o uguale a&quot;,
        '''  &quot;LessThanOrEqualTo&quot;: &quot;Minore o uguale a&quot;,
        '''  &quot;Between&quot;: &quot;Compreso&quot;,
        '''  &quot;NotBetween&quot;: &quot;Non compreso&quot;,
        '''  &quot;IsEmpty&quot;: &quot;E&apos; vuoto&quot;,
        '''  &quot;NotIsEmpty&quot;: &quot;Non è vuoto&quot;,
        '''  &quot;IsNull&quot;: &quot;E&apos; nullo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RadGridLocalizeConfig() As String
            Get
                Return ResourceManager.GetString("RadGridLocalizeConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;rblAtLeastOne&quot;: &quot;0&quot;,
        '''	&quot;rblTextMatchMode&quot;: &quot;Contains&quot;,
        '''	&quot;rblClaim&quot;:  &quot;2&quot;,
        '''	&quot;rblClausola&quot;: &quot;AND&quot;
        '''}
        '''.
        '''</summary>
        Friend ReadOnly Property SearchProtocolRblDefaultValue() As String
            Get
                Return ResourceManager.GetString("SearchProtocolRblDefaultValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [
        '''	{
        '''		&quot;Name&quot;: &quot;Collaboration&quot;,
        '''		&quot;VisibilityChains&quot;: {
        '''			&quot;MainChain&quot;: false,
        '''			&quot;AttachmentsChain&quot;: false,
        '''			&quot;AnnexedChain&quot;: false
        '''		}
        '''	}
        '''].
        '''</summary>
        Friend ReadOnly Property SecureDocumentVisibilities() As String
            Get
                Return ResourceManager.GetString("SecureDocumentVisibilities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''    &quot;DOU&quot;: true,
        '''	&quot;SecurePaper&quot;: true
        '''}.
        '''</summary>
        Friend ReadOnly Property SecureDocumentWorkflowStatementVisibility() As String
            Get
                Return ResourceManager.GetString("SecureDocumentWorkflowStatementVisibility", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;ProtocolIconModality&quot;:0,&quot;ResolutionIconModality&quot;:0,&quot;DocumentSeriesIconModality&quot;:0,&quot;UDSIconModality&quot;:0}.
        '''</summary>
        Friend ReadOnly Property SignedIconRenderingModality() As String
            Get
                Return ResourceManager.GetString("SignedIconRenderingModality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [
        '''	{
        '''		&quot;Name&quot;: &quot;Collaboration&quot;,
        '''		&quot;VisibilityChains&quot;: {
        '''			&quot;MainChain&quot;: false,
        '''			&quot;AttachmentsChain&quot;: false,
        '''			&quot;AnnexedChain&quot;: false
        '''		}
        '''	}, 
        '''	{
        '''		&quot;Name&quot;: &quot;Desk&quot;,
        '''		&quot;VisibilityChains&quot;: {
        '''			&quot;MainChain&quot;: false
        '''		}
        '''	}
        '''].
        '''</summary>
        Friend ReadOnly Property TemplateDocumentVisibilities() As String
            Get
                Return ResourceManager.GetString("TemplateDocumentVisibilities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to         {
        '''        &quot;DocSuite&quot; : &quot;~/App_Themes/DocSuite2008/imgset16/WF_Docsuite.png&quot;,
        '''        }.
        '''</summary>
        Friend ReadOnly Property WorkflowActivityImages() As String
            Get
                Return ResourceManager.GetString("WorkflowActivityImages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;Areas&quot;: {
        '''    &quot;Protocol&quot;: {
        '''      &quot;Actions&quot;: {
        '''        &quot;Create&quot;: {
        '''          &quot;Page&quot;: &quot;~/Prot/ProtInserimento.aspx?Type=Prot&amp;Action=FromWorkflow&quot;,
        '''          &quot;Options&quot;: {
        '''            &quot;SecurityCheck&quot;: &quot;False&quot;,
        '''            &quot;Year&quot;: &quot;False&quot;,
        '''            &quot;Number&quot;: &quot;False&quot;
        '''          }
        '''        },
        '''        &quot;ToPEC&quot;: {
        '''          &quot;Page&quot;: &quot;~/PEC/PECInsert.aspx?Type=Pec&amp;SimpleMode=True&amp;Year={0}&amp;Number={1}&quot;,
        '''          &quot;Options&quot;: {
        '''            &quot;SecurityCheck&quot;: &quot;False&quot;,
        '''            &quot;Year&quot;: &quot;True&quot;,
        '''       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WorkflowOperationConfig() As String
            Get
                Return ResourceManager.GetString("WorkflowOperationConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;xsl:stylesheet 
        '''	version=&quot;1.1&quot; 
        '''	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; 
        '''	xmlns:a=&quot;http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2&quot;&gt;
        '''	&lt;xsl:output method=&quot;html&quot; /&gt;
        '''
        '''	&lt;xsl:template name=&quot;FormatDate&quot;&gt;
        '''		&lt;xsl:param name=&quot;DateTime&quot; /&gt;
        '''
        '''		&lt;xsl:variable name=&quot;year&quot; select=&quot;substring($DateTime,1,4)&quot; /&gt;
        '''		&lt;xsl:variable name=&quot;month&quot; select=&quot;substring($DateTime,6,2)&quot; /&gt;
        '''		&lt;xsl:variable name=&quot;day&quot; select=&quot;substring($DateTime,9,2)&quot; /&gt;
        '''
        '''		&lt;xsl:value-of select=&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XSL_AGID_1_2() As String
            Get
                Return ResourceManager.GetString("XSL_AGID_1_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;xsl:stylesheet
        '''	version=&quot;2.0&quot;
        '''	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        '''	xmlns:b=&quot;http://www.fatturapa.gov.it/sdi/fatturapa/v1.1&quot;
        '''	xmlns:c=&quot;http://www.fatturapa.gov.it/sdi/fatturapa/v1.0&quot;
        '''	xmlns:a=&quot;http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2&quot;
        '''	xmlns:d=&quot;http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0&quot;&gt;
        '''
        '''  &lt;xsl:output method=&quot;xhtml&quot; /&gt;
        '''  &lt;xsl:decimal-format name=&quot;euro&quot; decimal-separator=&quot;,&quot; grouping-separator=&quot;.&quot;/&gt;
        '''
        '''  &lt;xsl:template nam [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XSL_AssoSoftware_1_2() As String
            Get
                Return ResourceManager.GetString("XSL_AssoSoftware_1_2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
