//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblosDS.UnitTest.LegalExtension.LegalExtension {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BiblosDS.WCF.Interface")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LegalExtension.IServiceLegalExtension")]
    public interface IServiceLegalExtension {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLegalExtension/GetData", ReplyAction="http://tempuri.org/IServiceLegalExtension/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLegalExtension/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceLegalExtension/GetDataUsingDataContractResponse")]
        BiblosDS.UnitTest.LegalExtension.LegalExtension.CompositeType GetDataUsingDataContract(BiblosDS.UnitTest.LegalExtension.LegalExtension.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLegalExtension/IsAlive", ReplyAction="http://tempuri.org/IServiceLegalExtension/IsAliveResponse")]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLegalExtension/VerifyConservation", ReplyAction="http://tempuri.org/IServiceLegalExtension/VerifyConservationResponse")]
        bool VerifyConservation(System.Guid IdConservazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLegalExtension/VerifyTaskOfConservation", ReplyAction="http://tempuri.org/IServiceLegalExtension/VerifyTaskOfConservationResponse")]
        bool VerifyTaskOfConservation(System.Guid IdTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLegalExtension/DoTaskOfConservation", ReplyAction="http://tempuri.org/IServiceLegalExtension/DoTaskOfConservationResponse")]
        bool DoTaskOfConservation(System.Guid IdTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLegalExtension/ConfirmSignedConservation", ReplyAction="http://tempuri.org/IServiceLegalExtension/ConfirmSignedConservationResponse")]
        bool ConfirmSignedConservation(System.Guid IdConservazione);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLegalExtensionChannel : BiblosDS.UnitTest.LegalExtension.LegalExtension.IServiceLegalExtension, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLegalExtensionClient : System.ServiceModel.ClientBase<BiblosDS.UnitTest.LegalExtension.LegalExtension.IServiceLegalExtension>, BiblosDS.UnitTest.LegalExtension.LegalExtension.IServiceLegalExtension {
        
        public ServiceLegalExtensionClient() {
        }
        
        public ServiceLegalExtensionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLegalExtensionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLegalExtensionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLegalExtensionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public BiblosDS.UnitTest.LegalExtension.LegalExtension.CompositeType GetDataUsingDataContract(BiblosDS.UnitTest.LegalExtension.LegalExtension.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public bool VerifyConservation(System.Guid IdConservazione) {
            return base.Channel.VerifyConservation(IdConservazione);
        }
        
        public bool VerifyTaskOfConservation(System.Guid IdTask) {
            return base.Channel.VerifyTaskOfConservation(IdTask);
        }
        
        public bool DoTaskOfConservation(System.Guid IdTask) {
            return base.Channel.DoTaskOfConservation(IdTask);
        }
        
        public bool ConfirmSignedConservation(System.Guid IdConservazione) {
            return base.Channel.ConfirmSignedConservation(IdConservazione);
        }
    }
}
