'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Viewers

    Partial Public Class ViewerLight

        '''<summary>
        '''RadCodeBlock1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock

        '''<summary>
        '''RadWindowManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadWindowManager As Global.Telerik.Web.UI.RadWindowManager

        '''<summary>
        '''windowStartWorkflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents windowStartWorkflow As Global.Telerik.Web.UI.RadWindow

        '''<summary>
        '''windowModifyPrivacyLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents windowModifyPrivacyLevel As Global.Telerik.Web.UI.RadWindow

        '''<summary>
        '''paneToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents paneToolbar As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''ToolBar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolBar As Global.Telerik.Web.UI.RadToolBar

        '''<summary>
        '''pnlMessageBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMessageBox As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''timerMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents timerMessage As Global.System.Web.UI.Timer

        '''<summary>
        '''messageBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents messageBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''messageText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents messageText As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RadPageSplitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageSplitter As Global.Telerik.Web.UI.RadSplitter

        '''<summary>
        '''LeftPane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LeftPane As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''rtvListDocument control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtvListDocument As Global.Telerik.Web.UI.RadTreeView

        '''<summary>
        '''multiPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents multiPages As Global.Telerik.Web.UI.RadSplitter

        '''<summary>
        '''rtvListDocumentContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtvListDocumentContainer As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''tabStripViews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabStripViews As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''SplitBar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SplitBar As Global.Telerik.Web.UI.RadSplitBar

        '''<summary>
        '''PDFPane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PDFPane As Global.Telerik.Web.UI.RadPane

        '''<summary>
        '''PdfSRC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PdfSRC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fake control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fake As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
