//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("DocumentoSanitario", Namespace="", IsNullable=false)]
public partial class DocumentoSanitarioType {
    
    private ChiaveType chiaveField;
    
    private ComponenteType componenteField;
    
    private DatiType datiField;
    
    private RevisioneType revisioneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ChiaveType Chiave {
        get {
            return this.chiaveField;
        }
        set {
            this.chiaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComponenteType Componente {
        get {
            return this.componenteField;
        }
        set {
            this.componenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DatiType Dati {
        get {
            return this.datiField;
        }
        set {
            this.datiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RevisioneType Revisione {
        get {
            return this.revisioneField;
        }
        set {
            this.revisioneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChiaveType {
    
    private string numeroField;
    
    private int annoField;
    
    private string archivioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Anno {
        get {
            return this.annoField;
        }
        set {
            this.annoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Archivio {
        get {
            return this.archivioField;
        }
        set {
            this.archivioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RevisioneType {
    
    private RevisioneTypeOperazione operazioneField;
    
    private string iDRefertoPrincipaleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RevisioneTypeOperazione Operazione {
        get {
            return this.operazioneField;
        }
        set {
            this.operazioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IDRefertoPrincipale {
        get {
            return this.iDRefertoPrincipaleField;
        }
        set {
            this.iDRefertoPrincipaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum RevisioneTypeOperazione {
    
    /// <remarks/>
    SOSTITUZIONE,
    
    /// <remarks/>
    ANNULLAMENTO,
    
    /// <remarks/>
    INTEGRAZIONE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatiType {
    
    private System.DateTime dataOraRefertoField;
    
    private string erogatoreField;
    
    private string erogatoreDescrizioneField;
    
    private string settoreErogatoreField;
    
    private string settoreErogatoreDescrizioneField;
    
    private string richiedenteField;
    
    private string richiedenteDescrizioneField;
    
    private string regimeField;
    
    private string medicoRefertanteField;
    
    private string medicoRefertanteDescrizioneField;
    
    private string iDAssistitoSACField;
    
    private string cognomeField;
    
    private string nomeField;
    
    private DatiTypeSesso sessoField;
    
    private string dataNascitaField;
    
    private string comuneNascitaField;
    
    private string codiceFiscaleField;
    
    private string iDPrenotazioneField;
    
    private string iDEpisodioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime DataOraReferto {
        get {
            return this.dataOraRefertoField;
        }
        set {
            this.dataOraRefertoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Erogatore {
        get {
            return this.erogatoreField;
        }
        set {
            this.erogatoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ErogatoreDescrizione {
        get {
            return this.erogatoreDescrizioneField;
        }
        set {
            this.erogatoreDescrizioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SettoreErogatore {
        get {
            return this.settoreErogatoreField;
        }
        set {
            this.settoreErogatoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SettoreErogatoreDescrizione {
        get {
            return this.settoreErogatoreDescrizioneField;
        }
        set {
            this.settoreErogatoreDescrizioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Richiedente {
        get {
            return this.richiedenteField;
        }
        set {
            this.richiedenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RichiedenteDescrizione {
        get {
            return this.richiedenteDescrizioneField;
        }
        set {
            this.richiedenteDescrizioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Regime {
        get {
            return this.regimeField;
        }
        set {
            this.regimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MedicoRefertante {
        get {
            return this.medicoRefertanteField;
        }
        set {
            this.medicoRefertanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MedicoRefertanteDescrizione {
        get {
            return this.medicoRefertanteDescrizioneField;
        }
        set {
            this.medicoRefertanteDescrizioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IDAssistitoSAC {
        get {
            return this.iDAssistitoSACField;
        }
        set {
            this.iDAssistitoSACField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Cognome {
        get {
            return this.cognomeField;
        }
        set {
            this.cognomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DatiTypeSesso Sesso {
        get {
            return this.sessoField;
        }
        set {
            this.sessoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataNascita {
        get {
            return this.dataNascitaField;
        }
        set {
            this.dataNascitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ComuneNascita {
        get {
            return this.comuneNascitaField;
        }
        set {
            this.comuneNascitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CodiceFiscale {
        get {
            return this.codiceFiscaleField;
        }
        set {
            this.codiceFiscaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IDPrenotazione {
        get {
            return this.iDPrenotazioneField;
        }
        set {
            this.iDPrenotazioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IDEpisodio {
        get {
            return this.iDEpisodioField;
        }
        set {
            this.iDEpisodioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum DatiTypeSesso {
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    U,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ComponenteType {
    
    private string filenameField;
    
    private string descrizioneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Descrizione {
        get {
            return this.descrizioneField;
        }
        set {
            this.descrizioneField = value;
        }
    }
}
