define(["require", "exports"], function (require, exports) {
    var UpdateActionType;
    (function (UpdateActionType) {
        UpdateActionType[UpdateActionType["FascicleClose"] = 0] = "FascicleClose";
        UpdateActionType[UpdateActionType["TemplateCollaborationPublish"] = 1] = "TemplateCollaborationPublish";
        UpdateActionType[UpdateActionType["RoleUserTemplateCollaborationInvalid"] = 2] = "RoleUserTemplateCollaborationInvalid";
        UpdateActionType[UpdateActionType["ActivityFascicleUpdate"] = 4] = "ActivityFascicleUpdate";
        UpdateActionType[UpdateActionType["ActivityFascicleClose"] = 8] = "ActivityFascicleClose";
        UpdateActionType[UpdateActionType["ProtocolArchivedUpdate"] = 16] = "ProtocolArchivedUpdate";
        UpdateActionType[UpdateActionType["HandlingWorkflow"] = 32] = "HandlingWorkflow";
        UpdateActionType[UpdateActionType["RelaseHandlingWorkflow"] = 64] = "RelaseHandlingWorkflow";
        UpdateActionType[UpdateActionType["RemoveFascicleFromDossierFolder"] = 128] = "RemoveFascicleFromDossierFolder";
        UpdateActionType[UpdateActionType["AssociatedFascicleToDossierFolder"] = 256] = "AssociatedFascicleToDossierFolder";
        UpdateActionType[UpdateActionType["CompleteDematerialisationWorkflow"] = 512] = "CompleteDematerialisationWorkflow";
        UpdateActionType[UpdateActionType["DossierFolderAuthorizationsPropagation"] = 1024] = "DossierFolderAuthorizationsPropagation";
        UpdateActionType[UpdateActionType["CompleteSecureDocumentWorkflow"] = 2048] = "CompleteSecureDocumentWorkflow";
        UpdateActionType[UpdateActionType["UpdateCategory"] = 4096] = "UpdateCategory";
        UpdateActionType[UpdateActionType["PeriodicFascicleClose"] = 8192] = "PeriodicFascicleClose";
        UpdateActionType[UpdateActionType["ActivateProtocol"] = 16384] = "ActivateProtocol";
        UpdateActionType[UpdateActionType["OpenFascicleClosed"] = 32768] = "OpenFascicleClosed";
        UpdateActionType[UpdateActionType["CancelFascicle"] = 65536] = "CancelFascicle";
        UpdateActionType[UpdateActionType["PECMailManaged"] = 131072] = "PECMailManaged";
        UpdateActionType[UpdateActionType["PECMailInvoiceTenantCorrection"] = 262144] = "PECMailInvoiceTenantCorrection";
        UpdateActionType[UpdateActionType["FascicleMoveToFolder"] = 524288] = "FascicleMoveToFolder";
        UpdateActionType[UpdateActionType["TenantContainerAdd"] = 1048576] = "TenantContainerAdd";
        UpdateActionType[UpdateActionType["TenantRoleAdd"] = 2097152] = "TenantRoleAdd";
        UpdateActionType[UpdateActionType["TenantContactAdd"] = 4194304] = "TenantContactAdd";
        UpdateActionType[UpdateActionType["TenantConfigurationAdd"] = 8388608] = "TenantConfigurationAdd";
        UpdateActionType[UpdateActionType["TenantPECMailBoxAdd"] = 16777216] = "TenantPECMailBoxAdd";
        UpdateActionType[UpdateActionType["TenantWorkflowRepositoryAdd"] = 33554432] = "TenantWorkflowRepositoryAdd";
        UpdateActionType[UpdateActionType["TenantContainerRemove"] = 67108864] = "TenantContainerRemove";
        UpdateActionType[UpdateActionType["TenantRoleRemove"] = 134217728] = "TenantRoleRemove";
        UpdateActionType[UpdateActionType["TenantConfigurationRemove"] = 268435456] = "TenantConfigurationRemove";
        UpdateActionType[UpdateActionType["TenantPECMailBoxRemove"] = 536870912] = "TenantPECMailBoxRemove";
        UpdateActionType[UpdateActionType["TenantWorkflowRepositoryRemove"] = 1073741824] = "TenantWorkflowRepositoryRemove";
        UpdateActionType[UpdateActionType["TenantContactRemove"] = 2147483648] = "TenantContactRemove";
        UpdateActionType[UpdateActionType["CollaborationManaged"] = 4294967296] = "CollaborationManaged";
        UpdateActionType[UpdateActionType["TenantContainerAddAll"] = 8589934592] = "TenantContainerAddAll";
        UpdateActionType[UpdateActionType["TenantContainerRemoveAll"] = 17179869184] = "TenantContainerRemoveAll";
        UpdateActionType[UpdateActionType["TenantRoleAddAll"] = 34359738368] = "TenantRoleAddAll";
        UpdateActionType[UpdateActionType["TenantRoleRemoveAll"] = 68719476736] = "TenantRoleRemoveAll";
        UpdateActionType[UpdateActionType["TenantContactAddAll"] = 137438953472] = "TenantContactAddAll";
        UpdateActionType[UpdateActionType["TenantContactRemoveAll"] = 274877906944] = "TenantContactRemoveAll";
        UpdateActionType[UpdateActionType["CloneProcessFolder"] = 549755813888] = "CloneProcessFolder";
        UpdateActionType[UpdateActionType["AssociatedProcessDossierFolderToFascicle"] = 1099511627776] = "AssociatedProcessDossierFolderToFascicle";
        UpdateActionType[UpdateActionType["ChangeFascicleType"] = 2199023255552] = "ChangeFascicleType";
    })(UpdateActionType || (UpdateActionType = {}));
    return UpdateActionType;
});
//# sourceMappingURL=UpdateActionType.js.map