//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Wide/WebService.nsf/TipoDocService.wsdl", ConfigurationName="TipoDocumentoService.TipoDocServicePortType")]
    public interface TipoDocServicePortType {
        
        // CODEGEN: Generating message contract since the operation TipoDocDocumento is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse1 TipoDocDocumento(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse1> TipoDocDocumentoAsync(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Wide/WebService.nsf/TipoDocService.wsdl")]
    public partial class TipoDocDocumentoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chiaveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Chiave {
            get {
                return this.chiaveField;
            }
            set {
                this.chiaveField = value;
                this.RaisePropertyChanged("Chiave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Wide/WebService.nsf/TipoDocService.wsdl")]
    public partial class Documento_Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("TipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Wide/WebService.nsf/TipoDocService.wsdl")]
    public partial class TipoDocDocumentoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Esito_Type esitoField;
        
        private Documento_Type[] documentoField;
        
        private string descrizioneErroreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Esito_Type esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("esito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Documento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Documento_Type[] Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DescrizioneErrore {
            get {
                return this.descrizioneErroreField;
            }
            set {
                this.descrizioneErroreField = value;
                this.RaisePropertyChanged("DescrizioneErrore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Wide/WebService.nsf/TipoDocService.wsdl")]
    public enum Esito_Type {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoDocDocumentoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wide/WebService.nsf/TipoDocService.wsdl", Order=0)]
        public VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest TipoDocDocumentoRequest;
        
        public TipoDocDocumentoRequest1() {
        }
        
        public TipoDocDocumentoRequest1(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest TipoDocDocumentoRequest) {
            this.TipoDocDocumentoRequest = TipoDocDocumentoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoDocDocumentoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wide/WebService.nsf/TipoDocService.wsdl", Order=0)]
        public VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse TipoDocDocumentoResponse;
        
        public TipoDocDocumentoResponse1() {
        }
        
        public TipoDocDocumentoResponse1(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse TipoDocDocumentoResponse) {
            this.TipoDocDocumentoResponse = TipoDocDocumentoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoDocServicePortTypeChannel : VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoDocServicePortTypeClient : System.ServiceModel.ClientBase<VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocServicePortType>, VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocServicePortType {
        
        public TipoDocServicePortTypeClient() {
        }
        
        public TipoDocServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoDocServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDocServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDocServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse1 VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocServicePortType.TipoDocDocumento(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1 request) {
            return base.Channel.TipoDocDocumento(request);
        }
        
        public VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse TipoDocDocumento(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest TipoDocDocumentoRequest) {
            VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1 inValue = new VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1();
            inValue.TipoDocDocumentoRequest = TipoDocDocumentoRequest;
            VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse1 retVal = ((VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocServicePortType)(this)).TipoDocDocumento(inValue);
            return retVal.TipoDocDocumentoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse1> VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocServicePortType.TipoDocDocumentoAsync(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1 request) {
            return base.Channel.TipoDocDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoResponse1> TipoDocDocumentoAsync(VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest TipoDocDocumentoRequest) {
            VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1 inValue = new VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocDocumentoRequest1();
            inValue.TipoDocDocumentoRequest = TipoDocDocumentoRequest;
            return ((VecompSoftware.BPM.Integrations.Modules.ENEA.Wide.TipoDocumentoService.TipoDocServicePortType)(this)).TipoDocDocumentoAsync(inValue);
        }
    }
}
