'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CollaborationVersioningManagement

    '''<summary>
    '''rcbScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbScripts As Global.Telerik.Web.UI.RadCodeBlock

    '''<summary>
    '''uscViewerLight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscViewerLight As Global.VecompSoftware.DocSuiteWeb.Gui.Viewers.ViewerLight

    '''<summary>
    '''uscCheckInDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscCheckInDocuments As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload

    '''<summary>
    '''wndMonitor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wndMonitor As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''txtMonitor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonitor As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cmdClearMonitor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClearMonitor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdCheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCheckOut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUndoCheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUndoCheckOut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdCheckIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCheckIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdCheckInManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCheckInManual As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdMonitor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMonitor As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''cmdViewCollaboration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdViewCollaboration As Global.System.Web.UI.WebControls.Button
End Class
