'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserFDQMultiple

    '''<summary>
    '''rsbFDQMultiple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsbFDQMultiple As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''hdnHasError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnHasError As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnComplete As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''chkAllegati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllegati As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''gvFDQMultiple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFDQMultiple As Global.VecompSoftware.DocSuiteWeb.Presentation.BindGrid

    '''<summary>
    '''btnFDQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFDQ As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCheckIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chkFVicario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFVicario As Global.System.Web.UI.WebControls.CheckBox
End Class
