//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18408
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace VecompSoftware.ENCO
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceAVCPSoap", Namespace = "http://tempuri.org/")]
    public partial class ServiceAVCP : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback PutOrganoDeliberanteOperationCompleted;

        private System.Threading.SendOrPostCallback PutDeliberaOperationCompleted;

        private System.Threading.SendOrPostCallback GetDatiAVCPOperationCompleted;

        /// <remarks/>
        public ServiceAVCP()
        {
            this.Url = "http://10.0.1.4:7800/WSDBPAVCP/ServiceAVCP.asmx";
        }

        /// <remarks/>
        public event PutOrganoDeliberanteCompletedEventHandler PutOrganoDeliberanteCompleted;

        /// <remarks/>
        public event PutDeliberaCompletedEventHandler PutDeliberaCompleted;

        /// <remarks/>
        public event GetDatiAVCPCompletedEventHandler GetDatiAVCPCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutOrganoDeliberante", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSDBPAVCPOutput PutOrganoDeliberante(WSDBPAVCPOrganiDelibernatiInput Servizio)
        {
            object[] results = this.Invoke("PutOrganoDeliberante", new object[] {
                        Servizio});
            return ((WSDBPAVCPOutput)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginPutOrganoDeliberante(WSDBPAVCPOrganiDelibernatiInput Servizio, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("PutOrganoDeliberante", new object[] {
                        Servizio}, callback, asyncState);
        }

        /// <remarks/>
        public WSDBPAVCPOutput EndPutOrganoDeliberante(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSDBPAVCPOutput)(results[0]));
        }

        /// <remarks/>
        public void PutOrganoDeliberanteAsync(WSDBPAVCPOrganiDelibernatiInput Servizio)
        {
            this.PutOrganoDeliberanteAsync(Servizio, null);
        }

        /// <remarks/>
        public void PutOrganoDeliberanteAsync(WSDBPAVCPOrganiDelibernatiInput Servizio, object userState)
        {
            if ((this.PutOrganoDeliberanteOperationCompleted == null))
            {
                this.PutOrganoDeliberanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutOrganoDeliberanteOperationCompleted);
            }
            this.InvokeAsync("PutOrganoDeliberante", new object[] {
                        Servizio}, this.PutOrganoDeliberanteOperationCompleted, userState);
        }

        private void OnPutOrganoDeliberanteOperationCompleted(object arg)
        {
            if ((this.PutOrganoDeliberanteCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutOrganoDeliberanteCompleted(this, new PutOrganoDeliberanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutDelibera", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSDBPAVCPOutput PutDelibera(WSDBPAVCPDelibereInput Atto)
        {
            object[] results = this.Invoke("PutDelibera", new object[] {
                        Atto});
            return ((WSDBPAVCPOutput)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginPutDelibera(WSDBPAVCPDelibereInput Atto, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("PutDelibera", new object[] {
                        Atto}, callback, asyncState);
        }

        /// <remarks/>
        public WSDBPAVCPOutput EndPutDelibera(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSDBPAVCPOutput)(results[0]));
        }

        /// <remarks/>
        public void PutDeliberaAsync(WSDBPAVCPDelibereInput Atto)
        {
            this.PutDeliberaAsync(Atto, null);
        }

        /// <remarks/>
        public void PutDeliberaAsync(WSDBPAVCPDelibereInput Atto, object userState)
        {
            if ((this.PutDeliberaOperationCompleted == null))
            {
                this.PutDeliberaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutDeliberaOperationCompleted);
            }
            this.InvokeAsync("PutDelibera", new object[] {
                        Atto}, this.PutDeliberaOperationCompleted, userState);
        }

        private void OnPutDeliberaOperationCompleted(object arg)
        {
            if ((this.PutDeliberaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutDeliberaCompleted(this, new PutDeliberaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDatiAVCP", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSDBPPubblicazioneOutput GetDatiAVCP(WSDBPAVCPPubblicazioneInput input)
        {
            object[] results = this.Invoke("GetDatiAVCP", new object[] {
                        input});
            return ((WSDBPPubblicazioneOutput)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDatiAVCP(WSDBPAVCPPubblicazioneInput input, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDatiAVCP", new object[] {
                        input}, callback, asyncState);
        }

        /// <remarks/>
        public WSDBPPubblicazioneOutput EndGetDatiAVCP(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSDBPPubblicazioneOutput)(results[0]));
        }

        /// <remarks/>
        public void GetDatiAVCPAsync(WSDBPAVCPPubblicazioneInput input)
        {
            this.GetDatiAVCPAsync(input, null);
        }

        /// <remarks/>
        public void GetDatiAVCPAsync(WSDBPAVCPPubblicazioneInput input, object userState)
        {
            if ((this.GetDatiAVCPOperationCompleted == null))
            {
                this.GetDatiAVCPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatiAVCPOperationCompleted);
            }
            this.InvokeAsync("GetDatiAVCP", new object[] {
                        input}, this.GetDatiAVCPOperationCompleted, userState);
        }

        private void OnGetDatiAVCPOperationCompleted(object arg)
        {
            if ((this.GetDatiAVCPCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatiAVCPCompleted(this, new GetDatiAVCPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class WSDBPAVCPOrganiDelibernatiInput
    {

        private string codiceServizioField;

        private string descrizioneServizioField;

        /// <remarks/>
        public string CodiceServizio
        {
            get
            {
                return this.codiceServizioField;
            }
            set
            {
                this.codiceServizioField = value;
            }
        }

        /// <remarks/>
        public string DescrizioneServizio
        {
            get
            {
                return this.descrizioneServizioField;
            }
            set
            {
                this.descrizioneServizioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "DBP.DB.Objects.AVCP")]
    public partial class singoloType
    {

        private string itemField;

        private ItemChoiceType1 itemElementNameField;

        private string ragioneSocialeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codiceFiscale", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("identificativoFiscaleEstero", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ragioneSociale
        {
            get
            {
                return this.ragioneSocialeField;
            }
            set
            {
                this.ragioneSocialeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "DBP.DB.Objects.AVCP", IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":codiceFiscale")]
        codiceFiscale,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":identificativoFiscaleEstero")]
        identificativoFiscaleEstero,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "DBP.DB.Objects.AVCP")]
    public partial class aggregatoType
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string ragioneSocialeField;

        private ruoloType ruoloField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codiceFiscale", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("identificativoFiscaleEstero", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ragioneSociale
        {
            get
            {
                return this.ragioneSocialeField;
            }
            set
            {
                this.ragioneSocialeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ruoloType ruolo
        {
            get
            {
                return this.ruoloField;
            }
            set
            {
                this.ruoloField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "DBP.DB.Objects.AVCP", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":codiceFiscale")]
        codiceFiscale,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":identificativoFiscaleEstero")]
        identificativoFiscaleEstero,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "DBP.DB.Objects.AVCP")]
    public enum ruoloType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01-MANDANTE")]
        Item01MANDANTE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02-MANDATARIA")]
        Item02MANDATARIA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03-ASSOCIATA")]
        Item03ASSOCIATA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04-CAPOGRUPPO")]
        Item04CAPOGRUPPO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05-CONSORZIATA")]
        Item05CONSORZIATA,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "legge190_1_0")]
    public partial class raggruppamentoType
    {

        private aggregatoType[] membroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("membro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public aggregatoType[] membro
        {
            get
            {
                return this.membroField;
            }
            set
            {
                this.membroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "DBP.DB.Objects.AVCP")]
    public partial class pubblicazione
    {

        private pubblicazioneMetadata metadataField;

        private ArrayOfPubblicazioneLottoLotto[] dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pubblicazioneMetadata metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("lotto", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ArrayOfPubblicazioneLottoLotto[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DBP.DB.Objects.AVCP")]
    public partial class pubblicazioneMetadata
    {

        private string titoloField;

        private string abstractField;

        private System.DateTime dataPubbicazioneDatasetField;

        private string entePubblicatoreField;

        private System.DateTime dataUltimoAggiornamentoDatasetField;

        private int annoRiferimentoField;

        private string urlFileField;

        private object licenzaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titolo
        {
            get
            {
                return this.titoloField;
            }
            set
            {
                this.titoloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime dataPubbicazioneDataset
        {
            get
            {
                return this.dataPubbicazioneDatasetField;
            }
            set
            {
                this.dataPubbicazioneDatasetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entePubblicatore
        {
            get
            {
                return this.entePubblicatoreField;
            }
            set
            {
                this.entePubblicatoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime dataUltimoAggiornamentoDataset
        {
            get
            {
                return this.dataUltimoAggiornamentoDatasetField;
            }
            set
            {
                this.dataUltimoAggiornamentoDatasetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int annoRiferimento
        {
            get
            {
                return this.annoRiferimentoField;
            }
            set
            {
                this.annoRiferimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string urlFile
        {
            get
            {
                return this.urlFileField;
            }
            set
            {
                this.urlFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object licenza
        {
            get
            {
                return this.licenzaField;
            }
            set
            {
                this.licenzaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DBP.DB.Objects.AVCP")]
    public partial class ArrayOfPubblicazioneLottoLotto
    {

        private string cigField;

        private ArrayOfPubblicazioneLottoLottoStrutturaProponente strutturaProponenteField;

        private string oggettoField;

        private sceltaContraenteType sceltaContraenteField;

        private ArrayOfPubblicazioneLottoLottoPartecipanti partecipantiField;

        private ArrayOfPubblicazioneLottoLottoAggiudicatari aggiudicatariField;

        private decimal importoAggiudicazioneField;

        private ArrayOfPubblicazioneLottoLottoTempiCompletamento tempiCompletamentoField;

        private decimal importoSommeLiquidateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cig
        {
            get
            {
                return this.cigField;
            }
            set
            {
                this.cigField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfPubblicazioneLottoLottoStrutturaProponente strutturaProponente
        {
            get
            {
                return this.strutturaProponenteField;
            }
            set
            {
                this.strutturaProponenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oggetto
        {
            get
            {
                return this.oggettoField;
            }
            set
            {
                this.oggettoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sceltaContraenteType sceltaContraente
        {
            get
            {
                return this.sceltaContraenteField;
            }
            set
            {
                this.sceltaContraenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfPubblicazioneLottoLottoPartecipanti partecipanti
        {
            get
            {
                return this.partecipantiField;
            }
            set
            {
                this.partecipantiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfPubblicazioneLottoLottoAggiudicatari aggiudicatari
        {
            get
            {
                return this.aggiudicatariField;
            }
            set
            {
                this.aggiudicatariField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal importoAggiudicazione
        {
            get
            {
                return this.importoAggiudicazioneField;
            }
            set
            {
                this.importoAggiudicazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfPubblicazioneLottoLottoTempiCompletamento tempiCompletamento
        {
            get
            {
                return this.tempiCompletamentoField;
            }
            set
            {
                this.tempiCompletamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal importoSommeLiquidate
        {
            get
            {
                return this.importoSommeLiquidateField;
            }
            set
            {
                this.importoSommeLiquidateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DBP.DB.Objects.AVCP")]
    public partial class ArrayOfPubblicazioneLottoLottoStrutturaProponente
    {

        private string codiceFiscalePropField;

        private string denominazioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codiceFiscaleProp
        {
            get
            {
                return this.codiceFiscalePropField;
            }
            set
            {
                this.codiceFiscalePropField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string denominazione
        {
            get
            {
                return this.denominazioneField;
            }
            set
            {
                this.denominazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "DBP.DB.Objects.AVCP")]
    public enum sceltaContraenteType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01-PROCEDURA APERTA")]
        Item01PROCEDURAAPERTA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02-PROCEDURA RISTRETTA")]
        Item02PROCEDURARISTRETTA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03-PROCEDURA NEGOZIATA PREVIA PUBBLICAZIONE DEL BANDO")]
        Item03PROCEDURANEGOZIATAPREVIAPUBBLICAZIONEDELBANDO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04-PROCEDURA NEGOZIATA SENZA PREVIA PUBBLICAZIONE DEL BANDO")]
        Item04PROCEDURANEGOZIATASENZAPREVIAPUBBLICAZIONEDELBANDO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05-DIALOGO COMPETITIVO")]
        Item05DIALOGOCOMPETITIVO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06-PROCEDURA NEGOZIATA SENZA PREVIA INDIZIONE DI  GARA ART. 221 D.LGS. 163/2006")]
        Item06PROCEDURANEGOZIATASENZAPREVIAINDIZIONEDIGARAART221DLGS1632006,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07-SISTEMA DINAMICO DI ACQUISIZIONE")]
        Item07SISTEMADINAMICODIACQUISIZIONE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08-AFFIDAMENTO IN ECONOMIA - COTTIMO FIDUCIARIO")]
        Item08AFFIDAMENTOINECONOMIACOTTIMOFIDUCIARIO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14-PROCEDURA SELETTIVA EX ART 238 C.7, D.LGS. 163/2006")]
        Item14PROCEDURASELETTIVAEXART238C7DLGS1632006,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17-AFFIDAMENTO DIRETTO EX ART. 5 DELLA LEGGE N.381/91")]
        Item17AFFIDAMENTODIRETTOEXART5DELLALEGGEN38191,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21-PROCEDURA RISTRETTA DERIVANTE DA AVVISI CON CUI SI INDICE LA GARA")]
        Item21PROCEDURARISTRETTADERIVANTEDAAVVISICONCUISIINDICELAGARA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22-PROCEDURA NEGOZIATA DERIVANTE DA AVVISI CON CUI SI INDICE LA GARA")]
        Item22PROCEDURANEGOZIATADERIVANTEDAAVVISICONCUISIINDICELAGARA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23-AFFIDAMENTO IN ECONOMIA - AFFIDAMENTO DIRETTO")]
        Item23AFFIDAMENTOINECONOMIAAFFIDAMENTODIRETTO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24-AFFIDAMENTO DIRETTO A SOCIETA\' IN HOUSE")]
        Item24AFFIDAMENTODIRETTOASOCIETAINHOUSE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25-AFFIDAMENTO DIRETTO A SOCIETA\' RAGGRUPPATE/CONSORZIATE O CONTROLLATE NELLE CON" +
            "CESSIONI DI LL.PP")]
        Item25AFFIDAMENTODIRETTOASOCIETARAGGRUPPATECONSORZIATEOCONTROLLATENELLECONCESSIONIDILLPP,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26-AFFIDAMENTO DIRETTO IN ADESIONE AD ACCORDO QUADRO/CONVENZIONE")]
        Item26AFFIDAMENTODIRETTOINADESIONEADACCORDOQUADROCONVENZIONE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-CONFRONTO COMPETITIVO IN ADESIONE AD ACCORDO QUADRO/CONVENZIONE")]
        Item27CONFRONTOCOMPETITIVOINADESIONEADACCORDOQUADROCONVENZIONE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28-PROCEDURA AI SENSI DEI REGOLAMENTI DEGLI ORGANI COSTITUZIONALI")]
        Item28PROCEDURAAISENSIDEIREGOLAMENTIDEGLIORGANICOSTITUZIONALI,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DBP.DB.Objects.AVCP")]
    public partial class ArrayOfPubblicazioneLottoLottoPartecipanti
    {

        private raggruppamentoType[] raggruppamentoField;

        private singoloType[] partecipanteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("raggruppamento", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public raggruppamentoType[] raggruppamento
        {
            get
            {
                return this.raggruppamentoField;
            }
            set
            {
                this.raggruppamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partecipante", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public singoloType[] partecipante
        {
            get
            {
                return this.partecipanteField;
            }
            set
            {
                this.partecipanteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DBP.DB.Objects.AVCP")]
    public partial class ArrayOfPubblicazioneLottoLottoAggiudicatari
    {

        private raggruppamentoType[] aggiudicatarioRaggruppamentoField;

        private singoloType[] aggiudicatarioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aggiudicatarioRaggruppamento", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public raggruppamentoType[] aggiudicatarioRaggruppamento
        {
            get
            {
                return this.aggiudicatarioRaggruppamentoField;
            }
            set
            {
                this.aggiudicatarioRaggruppamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aggiudicatario", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public singoloType[] aggiudicatario
        {
            get
            {
                return this.aggiudicatarioField;
            }
            set
            {
                this.aggiudicatarioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "DBP.DB.Objects.AVCP")]
    public partial class ArrayOfPubblicazioneLottoLottoTempiCompletamento
    {

        private System.DateTime dataInizioField;

        private bool dataInizioFieldSpecified;

        private System.DateTime dataUltimazioneField;

        private bool dataUltimazioneFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime dataInizio
        {
            get
            {
                return this.dataInizioField;
            }
            set
            {
                this.dataInizioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataInizioSpecified
        {
            get
            {
                return this.dataInizioFieldSpecified;
            }
            set
            {
                this.dataInizioFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        public System.DateTime dataUltimazione
        {
            get
            {
                return this.dataUltimazioneField;
            }
            set
            {
                this.dataUltimazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUltimazioneSpecified
        {
            get
            {
                return this.dataUltimazioneFieldSpecified;
            }
            set
            {
                this.dataUltimazioneFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class WSDBPPubblicazioneOutput
    {

        private bool attoConclusoField;

        private pubblicazione datiAvcpField;

        private WSDBPAVCPResult resultField;

        /// <remarks/>
        public bool AttoConcluso
        {
            get
            {
                return this.attoConclusoField;
            }
            set
            {
                this.attoConclusoField = value;
            }
        }

        /// <remarks/>
        public pubblicazione DatiAvcp
        {
            get
            {
                return this.datiAvcpField;
            }
            set
            {
                this.datiAvcpField = value;
            }
        }

        /// <remarks/>
        public WSDBPAVCPResult Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class WSDBPAVCPResult
    {

        private int returnCodeField;

        private string returnCodeDescriptionField;

        /// <remarks/>
        public int ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string ReturnCodeDescription
        {
            get
            {
                return this.returnCodeDescriptionField;
            }
            set
            {
                this.returnCodeDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class WSDBPAVCPPubblicazioneInput
    {

        private string codiceServizioField;

        private int annoAttoField;

        private int numeroAttoField;

        /// <remarks/>
        public string CodiceServizio
        {
            get
            {
                return this.codiceServizioField;
            }
            set
            {
                this.codiceServizioField = value;
            }
        }

        /// <remarks/>
        public int AnnoAtto
        {
            get
            {
                return this.annoAttoField;
            }
            set
            {
                this.annoAttoField = value;
            }
        }

        /// <remarks/>
        public int NumeroAtto
        {
            get
            {
                return this.numeroAttoField;
            }
            set
            {
                this.numeroAttoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class WSDBPAVCPDelibereInput
    {

        private string codiceServizioField;

        private int annoAttoField;

        private int numeroAttoField;

        private System.DateTime dataAttoField;

        private string tipoAttoField;

        private string oggettoField;

        private string linkEsternoField;

        private string segnaturaField;

        private string codiceEsternoAttoField;

        /// <remarks/>
        public string CodiceServizio
        {
            get
            {
                return this.codiceServizioField;
            }
            set
            {
                this.codiceServizioField = value;
            }
        }

        /// <remarks/>
        public int AnnoAtto
        {
            get
            {
                return this.annoAttoField;
            }
            set
            {
                this.annoAttoField = value;
            }
        }

        /// <remarks/>
        public int NumeroAtto
        {
            get
            {
                return this.numeroAttoField;
            }
            set
            {
                this.numeroAttoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataAtto
        {
            get
            {
                return this.dataAttoField;
            }
            set
            {
                this.dataAttoField = value;
            }
        }

        /// <remarks/>
        public string TipoAtto
        {
            get
            {
                return this.tipoAttoField;
            }
            set
            {
                this.tipoAttoField = value;
            }
        }

        /// <remarks/>
        public string Oggetto
        {
            get
            {
                return this.oggettoField;
            }
            set
            {
                this.oggettoField = value;
            }
        }

        /// <remarks/>
        public string LinkEsterno
        {
            get
            {
                return this.linkEsternoField;
            }
            set
            {
                this.linkEsternoField = value;
            }
        }

        /// <remarks/>
        public string Segnatura
        {
            get
            {
                return this.segnaturaField;
            }
            set
            {
                this.segnaturaField = value;
            }
        }

        /// <remarks/>
        public string CodiceEsternoAtto
        {
            get
            {
                return this.codiceEsternoAttoField;
            }
            set
            {
                this.codiceEsternoAttoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class WSDBPAVCPOutput
    {

        private WSDBPAVCPResult[] resultField;

        /// <remarks/>
        public WSDBPAVCPResult[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void PutOrganoDeliberanteCompletedEventHandler(object sender, PutOrganoDeliberanteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PutOrganoDeliberanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal PutOrganoDeliberanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSDBPAVCPOutput Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSDBPAVCPOutput)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void PutDeliberaCompletedEventHandler(object sender, PutDeliberaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PutDeliberaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal PutDeliberaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSDBPAVCPOutput Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSDBPAVCPOutput)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetDatiAVCPCompletedEventHandler(object sender, GetDatiAVCPCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatiAVCPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDatiAVCPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WSDBPPubblicazioneOutput Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WSDBPPubblicazioneOutput)(this.results[0]));
            }
        }
    }
}
