define(["require", "exports"], function (require, exports) {
    var TNoticeReturnCodeType;
    (function (TNoticeReturnCodeType) {
        TNoticeReturnCodeType[TNoticeReturnCodeType["NumeroSpedizioneDuplicato"] = -79812] = "NumeroSpedizioneDuplicato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["NumeroSpedizioneInternoLungo"] = -79811] = "NumeroSpedizioneInternoLungo";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ErroreInserimentoCoda"] = -79810] = "ErroreInserimentoCoda";
        TNoticeReturnCodeType[TNoticeReturnCodeType["NomeZIPNonValido"] = -79802] = "NomeZIPNonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["LunghezzaZILEccedeIlMassimo"] = -79801] = "LunghezzaZILEccedeIlMassimo";
        TNoticeReturnCodeType[TNoticeReturnCodeType["NessunFileRicevuto"] = -79800] = "NessunFileRicevuto";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ErroreRecuperoCDC"] = -79703] = "ErroreRecuperoCDC";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ErroreLetturaStatusRaccomandata"] = -79702] = "ErroreLetturaStatusRaccomandata";
        TNoticeReturnCodeType[TNoticeReturnCodeType["RaccomandataNonEsiste"] = -79701] = "RaccomandataNonEsiste";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ParametroCodeAssente"] = -79700] = "ParametroCodeAssente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ErroreLetturaProgressivoInvio"] = -79600] = "ErroreLetturaProgressivoInvio";
        TNoticeReturnCodeType[TNoticeReturnCodeType["IndirizzioIPNonRilevato"] = -79520] = "IndirizzioIPNonRilevato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["IndirizzioIPNonAutorizzato"] = -79500] = "IndirizzioIPNonAutorizzato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["CodiceClienteNonAutorizzato"] = -79430] = "CodiceClienteNonAutorizzato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TokenScaduto"] = -79420] = "TokenScaduto";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TokenNonValido"] = -79410] = "TokenNonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TokenNonEsiste"] = -79400] = "TokenNonEsiste";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TipoInvioAssente"] = -79399] = "TipoInvioAssente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["EstensioneFileNonValida"] = -79382] = "EstensioneFileNonValida";
        TNoticeReturnCodeType[TNoticeReturnCodeType["NomeAllegatoAssente"] = -79381] = "NomeAllegatoAssente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["EstensionePDFNonValida"] = -79380] = "EstensionePDFNonValida";
        TNoticeReturnCodeType[TNoticeReturnCodeType["FilePDFAssente"] = -79371] = "FilePDFAssente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["DimensionePDFAssente"] = -79370] = "DimensionePDFAssente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["NomePDFAssente"] = -79360] = "NomePDFAssente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Campo_CPF_NonValido"] = -79352] = "Campo_CPF_NonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Campo_Verificata_NonValido"] = -79351] = "Campo_Verificata_NonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["IndirizzoEmailNonPresente"] = -79350] = "IndirizzoEmailNonPresente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TelefonoDestinatarioNonValido"] = -79347] = "TelefonoDestinatarioNonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TelefonoDestinatarioAssente"] = -79346] = "TelefonoDestinatarioAssente";
        TNoticeReturnCodeType[TNoticeReturnCodeType["NazioneNonIndicata"] = -79345] = "NazioneNonIndicata";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ComuneNonIndicato"] = -79344] = "ComuneNonIndicato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["CAPNonIndicato"] = -79343] = "CAPNonIndicato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ProvinciaNonIndicata"] = -79342] = "ProvinciaNonIndicata";
        TNoticeReturnCodeType[TNoticeReturnCodeType["CivicoNonIndicato"] = -79341] = "CivicoNonIndicato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["IndirizzoSedeNonIndicato"] = -79340] = "IndirizzoSedeNonIndicato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["CampoMessaggioHTMLVuoto"] = -79330] = "CampoMessaggioHTMLVuoto";
        TNoticeReturnCodeType[TNoticeReturnCodeType["DenominazioneIncompleta_2"] = -79320] = "DenominazioneIncompleta_2";
        TNoticeReturnCodeType[TNoticeReturnCodeType["DenominazioneIncompleta_1"] = -79310] = "DenominazioneIncompleta_1";
        TNoticeReturnCodeType[TNoticeReturnCodeType["FormatoTrasmissioneNonValido"] = -79306] = "FormatoTrasmissioneNonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["IdCodiceNonValido"] = -79305] = "IdCodiceNonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["XMLNonValida"] = -79300] = "XMLNonValida";
        TNoticeReturnCodeType[TNoticeReturnCodeType["NonEsisteXML"] = -79200] = "NonEsisteXML";
        TNoticeReturnCodeType[TNoticeReturnCodeType["PartitaIvaNonValida"] = -79110] = "PartitaIvaNonValida";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ZipCorrotto"] = -79101] = "ZipCorrotto";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ZipNonValido"] = -79100] = "ZipNonValido";
        TNoticeReturnCodeType[TNoticeReturnCodeType["ExceptionDiSistema"] = -999] = "ExceptionDiSistema";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Riservato_6"] = -800] = "Riservato_6";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Riservato_5"] = -600] = "Riservato_5";
        TNoticeReturnCodeType[TNoticeReturnCodeType["IPNonRilevato"] = -520] = "IPNonRilevato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["IPNonAutorizzato"] = -500] = "IPNonAutorizzato";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TokenNonValido_3"] = -420] = "TokenNonValido_3";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TokenNonValido_2"] = -410] = "TokenNonValido_2";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TokenNonValido_1"] = -401] = "TokenNonValido_1";
        TNoticeReturnCodeType[TNoticeReturnCodeType["TokenRicevuto"] = -400] = "TokenRicevuto";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Riservato4"] = -300] = "Riservato4";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Riservato3"] = -200] = "Riservato3";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Riservato2"] = -101] = "Riservato2";
        TNoticeReturnCodeType[TNoticeReturnCodeType["Riservato1"] = -100] = "Riservato1";
        TNoticeReturnCodeType[TNoticeReturnCodeType["OK"] = 0] = "OK";
    })(TNoticeReturnCodeType || (TNoticeReturnCodeType = {}));
    return TNoticeReturnCodeType;
});
//# sourceMappingURL=TNoticeReturnCodeType.js.map