'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProtGestioneFatturePA

    '''<summary>
    '''filterTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterTable As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''dateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateFrom As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''dateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateTo As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''uscProtocolGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscProtocolGrid As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtGrid

    '''<summary>
    '''btnUpdateGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateGrid As Global.System.Web.UI.WebControls.Button
End Class
