'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProtCollegamenti

    '''<summary>
    '''rsb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsb As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''RadWindowManagerCollegamenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManagerCollegamenti As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''windowAddCollegamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowAddCollegamento As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''wndSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wndSearch As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''rsb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsb1 As Global.Telerik.Web.UI.RadScriptBlock

    '''<summary>
    '''tvwProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tvwProtocolLink As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''ContextMenuCollegamentiEmpty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContextMenuCollegamentiEmpty As Global.Telerik.Web.UI.RadTreeViewContextMenu

    '''<summary>
    '''ContextMenuCollegamentiCurrentProtocollo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContextMenuCollegamentiCurrentProtocollo As Global.Telerik.Web.UI.RadTreeViewContextMenu

    '''<summary>
    '''ContextMenuCollegamenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContextMenuCollegamenti As Global.Telerik.Web.UI.RadTreeViewContextMenu

    '''<summary>
    '''btnMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStampa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStampa As Global.System.Web.UI.WebControls.Button
End Class
