'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProtModifica
    
    '''<summary>
    '''RadScriptBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptBlock1 As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''pnlMainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMainContent As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''uscProtocollo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscProtocollo As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocollo
    
    '''<summary>
    '''uscDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscDocumento As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload
    
    '''<summary>
    '''uscAllegati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscAllegati As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload
    
    '''<summary>
    '''uscAnnexes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscAnnexes As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload
    
    '''<summary>
    '''tblEditContenitore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEditContenitore As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rcbContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbContainer As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cmbContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbContainer As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvContainer As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tblFascicoli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFascicoli As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblFascicoloCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFascicoloCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''uscFascicoli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscFascicoli As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel
    
    '''<summary>
    '''tblEditProtocolStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEditProtocolStatus As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''cmbProtocolStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProtocolStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''uscClassificatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscClassificatore As Global.VecompSoftware.DocSuiteWeb.Gui.uscClassificatore
    
    '''<summary>
    '''tblEditClassificazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEditClassificazione As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''uscSottoClassificatore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscSottoClassificatore As Global.VecompSoftware.DocSuiteWeb.Gui.uscClassificatore
    
    '''<summary>
    '''tblEditObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEditObject As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''uscObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscObject As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolObjectChanger
    
    '''<summary>
    '''tblOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOther As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''lblSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''uscSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscSubject As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSelText
    
    '''<summary>
    '''SelServiceCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelServiceCategory As Global.VecompSoftware.DocSuiteWeb.Gui.uscServiceCategory
    
    '''<summary>
    '''rowPubblica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowPubblica As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ckbPublication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbPublication As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtons As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnConferma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConferma As Global.System.Web.UI.WebControls.Button
End Class
