'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CommonSelContactOChart

    '''<summary>
    '''PanelProviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelProviders As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DropDownProviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownProviders As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ButtonReloadProviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonReloadProviders As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TextFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextFilter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonFilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblNoProviders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoProviders As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TreeViewItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreeViewItems As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''ButtonConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonConfirm As Global.System.Web.UI.WebControls.Button
End Class
