'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uscResolutionChange
    
    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''RadWindowManagerProtocollo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManagerProtocollo As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''windowSelProtocollo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelProtocollo As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''windowSelContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelContact As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''windowSelDraftSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelDraftSeries As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''windowSelRoleCollaborationProposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelRoleCollaborationProposer As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''rtvRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtvRoles As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''btnSelectRoleProposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSelectRoleProposer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DefaultLoadingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DefaultLoadingPanel As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''Container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tblType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblType As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rblType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''tblCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCategory As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''uscCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscCategory As Global.VecompSoftware.DocSuiteWeb.Gui.uscClassificatore
    
    '''<summary>
    '''trSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSubCategory As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''uscSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscSubCategory As Global.VecompSoftware.DocSuiteWeb.Gui.uscClassificatore
    
    '''<summary>
    '''tblObjectPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblObjectPrivacy As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lblObjectPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObjectPrivacy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblObjectPrivacyDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObjectPrivacyDetail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObjectPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObjectPrivacy As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblObject As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trObject As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObject As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''trNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNote As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''trIE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trIE As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''chkExecutive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExecutive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tblEconomicData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEconomicData As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPosition As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''rdpValidityDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpValidityDateFrom As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdpValidityDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpValidityDateTo As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''ddlBidType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBidType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSupplierCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplierCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSupplierDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplierDescription As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblService As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''uscProposerProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscProposerProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''tblPublicationLetterProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPublicationLetterProtocolLink As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''uscPublicationLetterProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscPublicationLetterProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''tblOCList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOCList As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''pnlOCSupervisoryBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCSupervisoryBoard As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkOCSupervisoryBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCSupervisoryBoard As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlOCConfSindaci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCConfSindaci As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkOCConfSindaci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCConfSindaci As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlOCRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCRegion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkOCRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCRegion As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlOCManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCManagement As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkOCManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCManagement As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlOCCorteConti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCCorteConti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkOCCorteConti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCCorteConti As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlOCOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOCOther As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkOCOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOCOther As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlOrganoControllo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOrganoControllo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tblOCSupervisoryBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOCSupervisoryBoard As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rdpSupervisoryBoardWarningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpSupervisoryBoardWarningDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''uscSupervisoryBoardProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscSupervisoryBoardProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''trOCSupervisoryBoardFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCSupervisoryBoardFile As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''uscOCSupervisoryBoardDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscOCSupervisoryBoardDocument As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload
    
    '''<summary>
    '''trOCSupervisoryBoardOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCSupervisoryBoardOpinion As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtOCSupervisoryBoardOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOCSupervisoryBoardOpinion As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblCorteDeiConti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCorteDeiConti As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rdpCorteDeiContiWarningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpCorteDeiContiWarningDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''uscCorteDeiContiProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscCorteDeiContiProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''tblOCConfSindaci control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOCConfSindaci As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rdpConfSindaciWarningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpConfSindaciWarningDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''uscConfSindaciProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscConfSindaciProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''tblOCRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOCRegion As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trOCRegionSpedizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCRegionSpedizione As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''rdpRegionWarningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpRegionWarningDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''uscRegionProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscRegionProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''trOCRegionRicezioneEScadenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCRegionRicezioneEScadenza As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''rdpRegionConfirmDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpRegionConfirmDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdpRegionWaitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpRegionWaitDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''trOCRegionRispostaEDGR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCRegionRispostaEDGR As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdRegionResponseDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdRegionResponseDateLabel As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''rdpRegionResponseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpRegionResponseDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''tdDGRLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDGRLabel As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdDGRtext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDGRtext As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''txtDGR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDGR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tdResponseProtocolLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdResponseProtocolLabel As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''tdResponseProtocolContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdResponseProtocolContent As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''uscRegionResponseProtocol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscRegionResponseProtocol As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''trOCREgionInvioChiarimenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCREgionInvioChiarimenti As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''rdpRegionInvioChiarimenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpRegionInvioChiarimenti As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''uscRegionInvioChiarimentiProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscRegionInvioChiarimentiProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''trRegionComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRegionComment As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlRegionComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegionComment As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trRegionDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRegionDocument As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''uscOCRegionDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscOCRegionDocument As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload
    
    '''<summary>
    '''trRegionOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRegionOpinion As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''tdRegionOpinionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdRegionOpinionText As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''txtRegionOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegionOpinion As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''trOCRegionNoteApprovazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCRegionNoteApprovazione As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtApprovalNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApprovalNote As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''trOCRegionNoteDecadimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCRegionNoteDecadimento As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtDeclineNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeclineNote As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblOCManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOCManagement As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rdpManagementWarningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpManagementWarningDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''uscManagementProtocolLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscManagementProtocolLink As Global.VecompSoftware.DocSuiteWeb.Gui.uscProtocolSelTree
    
    '''<summary>
    '''tblOCOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOCOther As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''txtOCOtherDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOCOtherDescription As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOC As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''rdpWarningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpWarningDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''txtWarningProt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarningProt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdpConfirmDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpConfirmDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''txtConfirmProt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmProt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdpWaitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpWaitDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdpResponseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpResponseDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''txtResponseProt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponseProt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trOCComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCComment As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlOCComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOCComment As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trOCDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCDocument As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''uscOCDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscOCDocument As Global.VecompSoftware.DocSuiteWeb.Gui.uscDocumentUpload
    
    '''<summary>
    '''trOCOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOCOpinion As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtOCOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOCOpinion As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblComunication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblComunication As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trContactDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContactDest As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''trDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDest As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''uscContactDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscContactDest As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel
    
    '''<summary>
    '''trAlternativeDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAlternativeDest As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtAlternativeDest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlternativeDest As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''trContactProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContactProp As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''pnlProponente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProponente As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''uscContactProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscContactProp As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel
    
    '''<summary>
    '''txtAlternativeProp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlternativeProp As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''uscRoleProposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscRoleProposer As Global.VecompSoftware.DocSuiteWeb.Gui.uscSettori
    
    '''<summary>
    '''trContactAss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContactAss As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''trAss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAss As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''uscContactAss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscContactAss As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel
    
    '''<summary>
    '''trAlternativeAss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAlternativeAss As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtAlternativeAss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlternativeAss As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''trContactMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContactMgr As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''trMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMgr As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''uscContactMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uscContactMgr As Global.VecompSoftware.DocSuiteWeb.Gui.uscContattiSel
    
    '''<summary>
    '''trAlternativeMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAlternativeMgr As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtAlternativeMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlternativeMgr As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblStatus As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''ddlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtChangedReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChangedReason As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''tblOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOther As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trContainer As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlIdContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdContainer As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''trPublication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPublication As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ckbPublication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbPublication As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlResolutionKind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResolutionKind As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlResolutionKind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResolutionKind As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlResolutionKindValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResolutionKindValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlAmmTrasp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAmmTrasp As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dgvResolutionKindDocumentSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvResolutionKindDocumentSeries As Global.Telerik.Web.UI.RadGrid
End Class
