'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uscResolutionBar

    '''<summary>
    '''tblButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblButtons As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''pnlButtonsDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtonsDocument As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnProposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProposta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnQuickDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuickDocument As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnToSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToSeries As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmSeries As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDoc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoc4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDoc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoc5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFrontespizio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFrontespizio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUltimaPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUltimaPagina As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPrivacyAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrivacyAttachments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPubblicaRevoca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPubblicaRevoca As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPublished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPublished As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteFrontespizio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteFrontespizio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDeleteUltimaPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteUltimaPagina As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLastPageUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLastPageUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlButtonsDefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtonsDefault As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnRolesRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRolesRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMailSettori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMailSettori As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStampa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStampa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDuplica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDuplica As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmView As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTakeCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTakeCharge As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rowBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBtn As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''pnlButtonsExtra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtonsExtra As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnPratica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPratica As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddToPratica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddToPratica As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFascicle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFascicle As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnModifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModifica As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFlushAnnexed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFlushAnnexed As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''inputElimina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputElimina As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAnnulla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnulla As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnWorkflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWorkflow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlToolbarPreView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlToolbarPreView As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnRegistrazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrazione As Global.System.Web.UI.WebControls.Button
End Class
