'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uscTenantsSelector
    
    '''<summary>
    '''rwTenantSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwTenantSelector As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''cmbSelectAzienda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSelectAzienda As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cmbSelectPecMailBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSelectPecMailBox As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cmbWorkflowRepositories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbWorkflowRepositories As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''btnContainerSelectorOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContainerSelectorOk As Global.Telerik.Web.UI.RadButton
End Class
