'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uscWorkflowDesignerValidations

    '''<summary>
    '''RadWindowManagerContacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManagerContacts As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''windowSelValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelValidation As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''windowSelModifyValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents windowSelModifyValidation As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''tblValidationRules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblValidationRules As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''tblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDSWMessageContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDSWMessageContainer As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDSWMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDSWMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''contentRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contentRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''actionToolbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actionToolbar As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''rtvValidationRules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtvValidationRules As Global.Telerik.Web.UI.RadTreeView
End Class
