//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VecompSoftware.JeepDashboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VecompSoftware.JeepService8")]
        public string ServiceName {
            get {
                return ((string)(this["ServiceName"]));
            }
            set {
                this["ServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VecompSoftware.JeepServiceLiveUpdate")]
        public string LiveUpdateServiceName {
            get {
                return ((string)(this["LiveUpdateServiceName"]));
            }
            set {
                this["LiveUpdateServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\sviluppo\\JS8\\JeepService\\JeepService\\bin\\Debug\\JeepService.exe")]
        public string JeepServicePath {
            get {
                return ((string)(this["JeepServicePath"]));
            }
            set {
                this["JeepServicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\sviluppo\\JS8\\JeepService\\JeepService\\bin\\Debug\\Config\\log4net.config")]
        public string log4netConfig {
            get {
                return ((string)(this["log4netConfig"]));
            }
            set {
                this["log4netConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\sviluppo\\JS8\\JeepService\\JeepService\\bin\\Debug\\Config\\JeepConfig.xml")]
        public string JeepServiceConfig {
            get {
                return ((string)(this["JeepServiceConfig"]));
            }
            set {
                this["JeepServiceConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Vecomp Software\\JeepService8\\LIVE UPDATE\\VecompSoftware.JeepServ" +
            "ice.LiveUpdate.exe")]
        public string LiveUpdatePath {
            get {
                return ((string)(this["LiveUpdatePath"]));
            }
            set {
                this["LiveUpdatePath"] = value;
            }
        }
    }
}
